### ISSUE TITLE
rollback is not happening when a runtime exception is occuring in transacted route in camel

### ISSUE THREAD

**Issue by maryam-eslahi** [jboss-fuse/redhat-fuse#51]
I have a transacted route which transform a message from a queue to a database with two tables. data should be added to both of tables or none of them, so I used .transacted() for doing that. 
also to check the behaviour of the .transacted() , I insert a bean to make a run time exception between two table updating bean in the middle of  the route. so a roll-back was expecting ,but the inserted row to the first table did not roll-back after runtime exception. 

my code is like this:

in my blueprint.xml:
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:cm="http://aries.apache.org/blueprint/xmlns/blueprint-cm/v1.3.0"
        xsi:schemaLocation="http://aries.apache.org/blueprint/xmlns/blueprint-cm/v1.3.0 http://aries.apache.org/schemas/blueprint-cm/blueprint-cm-1.3.0.xsd
             http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd
             http://camel.apache.org/schema/blueprint http://camel.apache.org/schema/blueprint/camel-blueprint.xsd"> 

        
        <bean id="myOrderService" class="org.jboss.fuse.quickstarts.beginner.camel.errorhandler.OrderService"/>

   <bean id="transactedJDBCRouteBuilder" class="com.hedleyproctor.www.TransactedJDBCRouteBuilder">
    	<argument ref="customerDAO"/>
    	<argument ref="addressDAO"/>
    </bean>
    
    <bean id="customerDAO" class="com.hedleyproctor.www.CustomerDAO">
    	<argument ref="jdbcTemplate"/>
    </bean>
    
    <bean id="addressDAO" class="com.hedleyproctor.www.AddressDAO">
    	<argument ref="jdbcTemplate"/>
</bean>
        <bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource"  >
  	  <property name="driverClassName" value="com.mysql.jdbc.Driver"/>
  	  <property name="url" value="jdbc:mysql://localhost:3306/BankDB"/>
  	  <property name="username" value="root"/>
  	  <property name="password" value="osslab"/> 
        </bean>
        <bean id="txManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
          <property name="dataSource" ref="dataSource"/>
        </bean>
	<bean id="jdbcTemplate" class="org.springframework.jdbc.core.JdbcTemplate">
		 <argument ref="dataSource"/>
        </bean>
      <bean id="myTransform" class="tutorial.MyTransform"/>
   <camelContext id="camel-jdbc-test" xmlns="http://camel.apache.org/schema/blueprint">
    <routeBuilder ref="transactedJDBCRouteBuilder"/>    
    </camelContext>

</blueprint>

in TransactedJDBCRouteBuilder:
package com.hedleyproctor.www;

import org.apache.camel.builder.RouteBuilder;

public class TransactedJDBCRouteBuilder extends RouteBuilder {

	private CustomerDAO customerDAO;
	private AddressDAO addressDAO;
	
	public TransactedJDBCRouteBuilder(CustomerDAO customerDAO, AddressDAO addressDAO) {
		this.customerDAO = customerDAO;
		this.addressDAO = addressDAO;
	}
	
	@Override
	public void configure() throws Exception {
		
		customerDAO.initCustomerTable();
		addressDAO.initAddressTable();
		
		/*import org.milyn.smooks.camel.dataformat.SmooksDataFormat;
SmooksDataFormat sdf = new SmooksDataFormat("smooks-config.xml");
		
		
		// read in customer data from a file, one customer per line
		from("file:c:/camel-transactions")
		.log("Picked up input file")
		// split each line of the file and convert it to an xml message using smooks
		.split().tokenize("\n")
			.log("Processing file line ${property.CamelSplitIndex} with content: ${body}")
			.unmarshal(sdf)
			.log("After unmarshal, message is ${body}")
			.to("activemq:customers.xml")
		.end()
		.log("Done reading input file");*/
		
		from("activemq:giro")
		.id("storeCustomerInDB")
		.transacted()
		.log("Storing customer info in DB")
		.setHeader("id",xpath("/order/customer/id/text()"))
		.setHeader("firstName",xpath("/order/customer/firstname/text()"))
		.setHeader("lastName",xpath("/order/customer/lastname/text()"))
		.to("bean:customerDAO?method=storeCustomer")
		.setHeader("street",xpath("/order/customer/street/text()"))
		.setHeader("town",xpath("/order/customer/town/text()"))
		.setHeader("postcode",xpath("/order/customer/postcode/text()"))
                .to("bean:myTransform?method=transform") 
		.to("bean:addressDAO?method=storeAddress")

  	}

}
 .to("bean:myTransform?method=transform") is for making runtime exception.

and in fuse: 
17:00:28.137 ERROR [Camel (camel-jdbc-test) thread #158 - JmsConsumer[giro]] Failed delivery for (MessageId: ID:localhost.localdomain-35004-1554631008591-41:34:1:1:1 on ExchangeId: ID-localhost-localdomain-1554630110105-96-1). Exhausted after delivery attempt: 1 caught: java.lang.Exception: test

java.lang.Exception: test
	at tutorial.MyTransform.transform(MyTransform.java:15) ~[2148:camel-jdbc-test-transactional-resource:7.0.0.fuse-000191-redhat-1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:481) ~[58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:300) ~[58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:273) ~[58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:187) ~[58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:53) ~[58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:41) ~[58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:406) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:176) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:220) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:101) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:114) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:220) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.spring.spi.TransactionErrorHandler$1.doInTransactionWithoutResult(TransactionErrorHandler.java:183) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34) [168:org.apache.servicemix.bundles.spring-tx:4.3.14.RELEASE_1]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [168:org.apache.servicemix.bundles.spring-tx:4.3.14.RELEASE_1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.doInTransactionTemplate(TransactionErrorHandler.java:176) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.processInTransaction(TransactionErrorHandler.java:136) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:105) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:114) [68:org.apache.camel.camel-spring:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97) [58:org.apache.camel.camel-core:2.21.0.fuse-000077-redhat-1]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:113) [792:org.apache.camel.camel-jms:2.21.0.fuse-000077-redhat-1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:719) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:679) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:649) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1166) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1158) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1055) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
17:00:28.148 WARN [Camel (camel-jdbc-test) thread #158 - JmsConsumer[giro]] Transaction rollback (0x43b4c4c1) redelivered(false) for (MessageId: ID:localhost.localdomain-35004-1554631008591-41:34:1:1:1 on ExchangeId: ID-localhost-localdomain-1554630110105-96-1) caught: java.lang.Exception: test
17:00:28.148 WARN [Camel (camel-jdbc-test) thread #158 - JmsConsumer[giro]] Execution of JMS message listener failed. Caused by: [org.apache.camel.RuntimeCamelException - java.lang.Exception: test]
org.apache.camel.RuntimeCamelException: java.lang.Exception: test
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1830) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler$1.doInTransactionWithoutResult(TransactionErrorHandler.java:190) ~[?:?]
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34) ~[168:org.apache.servicemix.bundles.spring-tx:4.3.14.RELEASE_1]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[168:org.apache.servicemix.bundles.spring-tx:4.3.14.RELEASE_1]
	at org.apache.camel.spring.spi.TransactionErrorHandler.doInTransactionTemplate(TransactionErrorHandler.java:176) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler.processInTransaction(TransactionErrorHandler.java:136) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:105) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:114) ~[?:?]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) ~[?:?]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) ~[?:?]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97) ~[?:?]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:113) ~[?:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:719) ~[593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:679) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:649) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1166) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1158) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1055) [593:org.apache.servicemix.bundles.spring-jms:4.3.14.RELEASE_1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.Exception: test
	at tutorial.MyTransform.transform(MyTransform.java:15) ~[2148:camel-jdbc-test-transactional-resource:7.0.0.fuse-000191-redhat-1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:481) ~[?:?]
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:300) ~[?:?]
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:273) ~[?:?]
	at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:187) ~[?:?]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:53) ~[?:?]
	at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:41) ~[?:?]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[?:?]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[?:?]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:406) ~[?:?]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:176) ~[?:?]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[?:?]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[?:?]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:220) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:101) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:114) ~[?:?]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:220) ~[?:?]
	at org.apache.camel.spring.spi.TransactionErrorHandler$1.doInTransactionWithoutResult(TransactionErrorHandler.java:183) ~[?:?]
	... 21 more

**Comment by zregvart** [comment]
Hi @hoonammaryam we don't use this use this issue tracker for support questions. Can I ask you to open a support case for the issue you're having at https://access.redhat.com/ or use Apache Camel [users mailing list](https://camel.apache.org/mailing-lists.html) to ask questions.
